import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home = () => {
    return (
        <>
            <Head>
                <title>Tailwind Test - Next.js</title>
                <meta
                    name={"description"}
                    content={"Generated by create next app"}
                />
                <meta
                    name={"viewport"}
                    content={"width=device-width, initial-scale=1"}
                />
                <link rel={"icon"} href={"/favicon.ico"} />
            </Head>
            <main className={"w-full min-h-screen"}>
                <div className={styles.center}>
                    <div
                        className={
                            "flex justify-center items-center w-full h-screen -mt-2"
                        }
                    >
                        <h1
                            className={
                                "text-5xl font-black bg-gradient-to-r from-sky-700 to-cyan-700 via-teal-500 bg-clip-text text-transparent animate-text"
                            }
                        >
                            Hello World!
                        </h1>
                    </div>
                </div>
            </main>
        </>
    );
}

export default Home;
